//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.UnityRoboticsDemo
{
    [Serializable]
    public class MyTwistStampedMsg : Message
    {
        public const string k_RosMessageName = "unity_robotics_demo_msgs/MyTwistStamped";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public Geometry.TwistMsg twist;

        public MyTwistStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.twist = new Geometry.TwistMsg();
        }

        public MyTwistStampedMsg(Std.HeaderMsg header, Geometry.TwistMsg twist)
        {
            this.header = header;
            this.twist = twist;
        }

        public static MyTwistStampedMsg Deserialize(MessageDeserializer deserializer) => new MyTwistStampedMsg(deserializer);

        private MyTwistStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            this.twist = Geometry.TwistMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.Write(this.twist);
        }

        public override string ToString()
        {
            return "MyTwistStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\ntwist: " + twist.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
